name: Illyrion CI/CD
run-name: "Illyrion CI/CD"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy_to_github_pages.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@main

      - id: setup_node
        name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - id: install_dependencies
        name: Install Dependencies
        run: npm install

      - id: optimize_svg
        name: Optimize SVG
        run: npx svgo -f src/assets/svg -o src/assets/svg

      - id: build_css
        name: Build CSS from SASS
        run: npx sass --style=compressed src/assets/sass/:src/assets/css/

      - id: remove_sass
        name: Remove SASS Folder
        run: rm -rf src/assets/sass/

      - id: setup_pages
        name: Setup Pages
        uses: actions/configure-pages@main

      - id: upload_artifact
        name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: "./src"

      - id: deploy_to_github_pages
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@main
